-- 由 dict/terms.json 自動產生(python scripts/gen_seed.py)
-- 可重複執行:以 (tw, cn, category) 為唯一鍵 upsert,整檔貼上 Run 即可
-- 新詞會 insert、既有詞更新 status/note,不會重複,也不動你捕捉的 pending 詞

-- 確保唯一鍵存在(schema.sql 已建則略過)
create unique index if not exists terms_seed_key_idx
  on public.terms (tw, cn, category);

insert into public.terms (tw, cn, category, status, note) values
  ('軟體', '软件', '資訊科技', 'confirmed', NULL),
  ('硬體', '硬件', '資訊科技', 'confirmed', NULL),
  ('韌體', '固件', '資訊科技', 'confirmed', 'firmware'),
  ('程式', '程序', '資訊科技', 'confirmed', '臺灣『程序』指 procedure/流程;中國『程序』兼指 program'),
  ('程式碼', '代码', '資訊科技', 'confirmed', 'code'),
  ('程式設計師', '程序员', '資訊科技', 'confirmed', '口語亦稱『碼農』,兩岸通用'),
  ('網路', '网络', '資訊科技', 'confirmed', NULL),
  ('網際網路', '互联网', '資訊科技', 'confirmed', 'Internet'),
  ('滑鼠', '鼠标', '資訊科技', 'confirmed', NULL),
  ('螢幕', '屏幕', '資訊科技', 'confirmed', NULL),
  ('記憶體', '内存', '資訊科技', 'confirmed', 'RAM'),
  ('硬碟', '硬盘', '資訊科技', 'confirmed', NULL),
  ('隨身碟', 'U盘', '資訊科技', 'confirmed', 'USB flash drive;中國亦稱『优盘』'),
  ('光碟', '光盘', '資訊科技', 'confirmed', NULL),
  ('印表機', '打印机', '資訊科技', 'confirmed', NULL),
  ('列印', '打印', '資訊科技', 'confirmed', NULL),
  ('解析度', '分辨率', '資訊科技', 'confirmed', NULL),
  ('數位', '数字', '資訊科技', 'confirmed', 'digital,如『數位相機』→『数码相机』'),
  ('資料', '数据', '資訊科技', 'confirmed', 'data'),
  ('資料庫', '数据库', '資訊科技', 'confirmed', NULL),
  ('字串', '字符串', '資訊科技', 'confirmed', 'string'),
  ('預設', '默认', '資訊科技', 'confirmed', 'default'),
  ('介面', '接口 / 界面', '資訊科技', 'confirmed', 'interface;軟體 UI 多用『界面』,程式 API 多用『接口』'),
  ('檔案', '文件', '資訊科技', 'confirmed', 'file;注意中國『文件』也指公文'),
  ('資料夾', '文件夹', '資訊科技', 'confirmed', 'folder'),
  ('解除安裝', '卸载', '資訊科技', 'confirmed', 'uninstall'),
  ('當機', '死机', '資訊科技', 'confirmed', 'crash/凍結;軟體閃退中國稱『崩溃』'),
  ('重灌', '重装', '資訊科技', 'confirmed', '重新安裝系統'),
  ('視窗', '窗口', '資訊科技', 'confirmed', 'window'),
  ('搜尋', '搜索', '資訊科技', 'confirmed', NULL),
  ('點選 / 按一下', '点击', '資訊科技', 'confirmed', 'click'),
  ('登入', '登录', '資訊科技', 'confirmed', 'log in'),
  ('帳號', '账号', '資訊科技', 'confirmed', 'account'),
  ('伺服器', '服务器', '資訊科技', 'confirmed', 'server'),
  ('雲端', '云', '資訊科技', 'confirmed', 'cloud,如『雲端硬碟』→『云盘』'),
  ('演算法', '算法', '資訊科技', 'confirmed', 'algorithm'),
  ('位元', '比特 / 位', '資訊科技', 'confirmed', 'bit'),
  ('位元組', '字节', '資訊科技', 'confirmed', 'byte'),
  ('連結', '链接', '資訊科技', 'confirmed', 'link'),
  ('上傳', '上传', '資訊科技', 'confirmed', NULL),
  ('智慧型手機', '智能手机', '資訊科技', 'confirmed', 'smartphone;『智慧』→『智能』,如智慧家庭→智能家居'),
  ('簡訊', '短信', '資訊科技', 'confirmed', 'SMS'),
  ('視訊', '视频', '資訊科技', 'confirmed', '中國『视频』泛指影片;臺灣『影片』中國亦稱『视频』'),
  ('影片', '视频', '資訊科技', 'confirmed', 'video clip'),
  ('部落格', '博客', '資訊科技', 'confirmed', 'blog'),
  ('部落客', '博主', '資訊科技', 'confirmed', 'blogger;『博主』泛指自媒體經營者'),
  ('駭客', '黑客', '資訊科技', 'confirmed', 'hacker'),
  ('雷射', '激光', '資訊科技', 'confirmed', 'laser'),
  ('工作列', '任务栏', '資訊科技', 'confirmed', 'taskbar'),
  ('桌布', '壁纸', '資訊科技', 'confirmed', 'wallpaper'),
  ('計程車', '出租车', '交通', 'confirmed', 'taxi;中國口語亦稱『打车』'),
  ('機車 / 摩托車', '摩托车', '交通', 'confirmed', '電動者中國稱『电动车 / 电瓶车』'),
  ('腳踏車 / 單車', '自行车', '交通', 'confirmed', 'bicycle'),
  ('公車', '公交车', '交通', 'confirmed', 'bus;中國亦稱『公交』'),
  ('捷運', '地铁', '交通', 'confirmed', 'metro/subway'),
  ('高鐵', '高铁', '交通', 'confirmed', '兩岸皆稱高鐵,但系統不同'),
  ('塞車', '堵车', '交通', 'confirmed', 'traffic jam'),
  ('斑馬線', '斑马线', '交通', 'confirmed', '兩岸同,正式為『人行横道』'),
  ('計程車資 / 車資', '车费', '交通', 'confirmed', NULL),
  ('冷氣', '空调', '生活用品', 'confirmed', 'air conditioner'),
  ('吹風機', '吹风机', '生活用品', 'confirmed', '兩岸同'),
  ('原子筆', '圆珠笔', '生活用品', 'confirmed', 'ballpoint pen'),
  ('立可白', '修正液 / 涂改液', '生活用品', 'confirmed', 'correction fluid'),
  ('橡皮擦', '橡皮', '生活用品', 'confirmed', 'eraser'),
  ('釘書機', '订书机', '生活用品', 'confirmed', 'stapler'),
  ('計算機', '计算器', '生活用品', 'confirmed', '⚠陷阱:臺灣『計算機』=calculator;中國『计算机』=電腦(computer)'),
  ('影印', '复印', '生活用品', 'confirmed', 'photocopy'),
  ('提款機', '取款机 / 自动取款机', '金融', 'confirmed', 'ATM;中國亦稱『ATM 机』'),
  ('提款', '取款', '金融', 'confirmed', 'withdraw'),
  ('鈔票', '钞票 / 纸币', '金融', 'confirmed', NULL),
  ('悠遊卡', '公交卡', '金融', 'confirmed', '交通儲值卡,各地名稱不同'),
  ('鳳梨', '菠萝', '飲食', 'confirmed', 'pineapple'),
  ('番茄', '西红柿', '飲食', 'confirmed', 'tomato;中國『番茄』亦通用'),
  ('馬鈴薯', '土豆', '飲食', 'confirmed', '⚠陷阱:中國『土豆』=馬鈴薯;臺灣『土豆』=花生'),
  ('高麗菜', '圆白菜 / 卷心菜', '飲食', 'confirmed', 'cabbage'),
  ('洋芋片', '薯片', '飲食', 'confirmed', 'potato chips'),
  ('泡麵', '方便面', '飲食', 'confirmed', 'instant noodles'),
  ('優格 / 優酪乳', '酸奶', '飲食', 'confirmed', 'yogurt'),
  ('鮪魚', '金枪鱼', '飲食', 'confirmed', 'tuna'),
  ('鮭魚', '三文鱼', '飲食', 'confirmed', 'salmon'),
  ('義大利麵', '意大利面 / 意面', '飲食', 'confirmed', 'pasta'),
  ('起司 / 乳酪', '奶酪', '飲食', 'confirmed', 'cheese;中國亦稱『芝士』(粵語借音)'),
  ('奇異果', '猕猴桃', '飲食', 'confirmed', 'kiwifruit'),
  ('酪梨', '牛油果', '飲食', 'confirmed', 'avocado'),
  ('便當', '盒饭', '飲食', 'confirmed', 'boxed meal;臺灣『便當』源自日語'),
  ('宵夜', '夜宵', '飲食', 'confirmed', '字序相反'),
  ('速食', '快餐', '飲食', 'confirmed', 'fast food'),
  ('鮮奶油', '淡奶油', '飲食', 'confirmed', 'whipping cream'),
  ('花椰菜', '西兰花 / 菜花', '飲食', 'confirmed', '綠色為西兰花(broccoli),白色為菜花(cauliflower)'),
  ('電視劇 / 連續劇', '电视剧', '影視娛樂', 'confirmed', NULL),
  ('卡通', '动画片', '影視娛樂', 'confirmed', 'cartoon'),
  ('男主角', '男主', '影視娛樂', 'confirmed', '中國習慣簡稱『男主/女主』'),
  ('預告片', '预告片', '影視娛樂', 'confirmed', 'trailer'),
  ('影集', '美剧 / 剧集', '影視娛樂', 'confirmed', '美國影集中國稱『美剧』'),
  ('直播主', '主播', '網路用語', 'confirmed', 'streamer;臺灣『主播』多指新聞主播'),
  ('網紅', '网红', '網路用語', 'confirmed', '兩岸通用,意同 influencer'),
  ('留言 / 回覆', '评论', '網路用語', 'confirmed', 'comment'),
  ('按讚', '点赞', '網路用語', 'confirmed', 'like'),
  ('訂閱', '订阅 / 关注', '網路用語', 'confirmed', '頻道追蹤中國多稱『关注』'),
  ('私訊', '私信', '網路用語', 'confirmed', 'DM'),
  ('梗圖', '表情包', '網路用語', 'confirmed', 'meme;『梗』本身臺灣用,中國亦借用'),
  ('滑手機', '刷手机', '網路用語', 'confirmed', '中國『刷』泛指滑動瀏覽,如『刷视频』'),
  ('好友 / 加好友', '好友 / 加好友', '網路用語', 'confirmed', '兩岸同'),
  ('視訊通話', '视频通话', '網路用語', 'confirmed', 'video call'),
  ('國小', '小学', '教育職場', 'confirmed', 'elementary school'),
  ('國中', '初中', '教育職場', 'confirmed', 'junior high'),
  ('大學部 / 大學生', '本科 / 本科生', '教育職場', 'confirmed', 'undergraduate;臺灣少用『本科』'),
  ('學測 / 指考', '高考', '教育職場', 'confirmed', '⚠非完全對等,僅功能類似(大學入學考)'),
  ('簡報 (檔)', 'PPT / 幻灯片 / 演示文稿', '教育職場', 'confirmed', 'presentation/slides'),
  ('報告', '汇报 / 报告', '教育職場', 'confirmed', '口頭進度多稱『汇报』'),
  ('薪水', '工资', '教育職場', 'confirmed', 'salary;臺灣亦稱『薪資』'),
  ('履歷', '简历', '教育職場', 'confirmed', 'resume/CV'),
  ('上班族', '上班族 / 打工人', '教育職場', 'confirmed', '『打工人』為中國近年流行語'),
  ('服務生', '服务员', '服務', 'confirmed', 'waiter/staff'),
  ('郵差', '邮递员', '服務', 'confirmed', 'mail carrier'),
  ('身分證', '身份证', '證件', 'confirmed', '字異:身分/身份'),
  ('戶口名簿', '户口本', '證件', 'confirmed', 'household register'),
  ('送出 / 提出 / 遞交 / 繳交', '提交', '常用詞', 'confirmed', 'submit;『提交』非臺灣慣用。臺灣依情境用:表單→送出、議案→提出/提案、仲裁訴訟→提付/提出、送件→遞交/繳交/申辦。查證:仲裁法用『提付仲裁』、公司法用『提案』,全文皆無『提交』'),
  ('品質', '质量', '常用詞', 'confirmed', '⚠陷阱:中國『质量』=品質(quality);臺灣『質量』=物理 mass'),
  ('機率', '概率', '常用詞', 'confirmed', 'probability'),
  ('範例', '例子 / 范例', '常用詞', 'confirmed', 'example'),
  ('厲害', '厉害 / 牛 / 牛逼', '口語', 'confirmed', '『牛逼(NB)』為粗俗強調語,正式場合避用'),
  ('很棒 / 讚', '很赞 / 给力', '口語', 'confirmed', '『给力』意為帶勁、夠力'),
  ('窩心', '暖心', '口語', 'confirmed', '⚠陷阱:臺灣『窩心』=溫暖貼心;中國『窝心』=憋屈難受,意思相反'),
  ('幹嘛', '干嘛 / 干啥', '口語', 'confirmed', '『干啥』偏北方口語'),
  ('搞定', '搞定', '口語', 'confirmed', '兩岸通用'),
  ('劃算', '划算 / 合算', '口語', 'confirmed', 'worth it'),
  ('公分', '厘米', '度量', 'confirmed', 'centimeter;『公分』為臺灣慣用,中國用『厘米』'),
  ('公尺', '米', '度量', 'confirmed', 'meter'),
  ('公釐 / 毫米', '毫米', '度量', 'confirmed', 'millimeter;臺灣口語『公釐』'),
  ('馬達', '电机 / 马达', '工程', 'confirmed', 'motor;正式中國多用『电机』'),
  ('品管', '质检 / 质控', '工程', 'confirmed', 'quality control'),
  ('規格', '规格 / 参数', '工程', 'confirmed', 'spec'),
  ('保固', '保修', '消費', 'confirmed', 'warranty'),
  ('發票', '发票', '消費', 'confirmed', '臺灣含統一發票兌獎制度,功能不同'),
  ('刷卡', '刷卡', '消費', 'confirmed', '兩岸同;行動支付中國更普及(扫码)'),
  ('宅配', '快递 / 配送', '消費', 'confirmed', 'delivery;臺灣『宅配』源自日語'),
  ('超商 / 便利商店', '便利店', '消費', 'confirmed', 'convenience store'),
  ('大賣場 / 量販店', '大卖场 / 超市', '消費', 'confirmed', 'hypermarket'),
  ('百貨公司', '百货 / 商场', '消費', 'confirmed', 'department store'),
  ('影片', '视频', '網路流行語', 'confirmed', '★最典型外溢詞:臺灣年輕人已大量改口說『視頻』而不自覺。YouTube/短影音一律『影片』'),
  ('馬上 / 立刻', '立马', '網路流行語', 'confirmed', '★『立馬』近年大量入侵臺灣口語'),
  ('訊息 / 資訊', '信息', '網路流行語', 'confirmed', 'message/information;臺灣 message=訊息、information=資訊'),
  ('高畫質 / 高解析度', '高清', '網路流行語', 'confirmed', 'HD'),
  ('啟用 / 啟動', '激活', '網路流行語', 'confirmed', 'activate'),
  ('卡卡的 / lag', '卡顿', '網路流行語', 'confirmed', 'lag/掉幀'),
  ('線上 / 上線', '在线', '網路流行語', 'confirmed', 'online,如『在線等』→『線上等』'),
  ('管道', '渠道', '網路流行語', 'confirmed', 'channel/途徑'),
  ('水準', '水平', '網路流行語', 'confirmed', 'level;臺灣『水平』多指物理水平面'),
  ('可靠 / 牢靠', '靠谱', '網路流行語', 'confirmed', '不靠谱=不可靠/不牢靠'),
  ('親民 / 貼近民眾', '接地气', '網路流行語', 'confirmed', 'down-to-earth'),
  ('外貌 / 長相', '颜值', '網路流行語', 'confirmed', '『顏值』已半通用,但源自中國網路'),
  ('招數 / 老梗 / 手段', '套路', '網路流行語', 'confirmed', 'trick/routine'),
  ('過度競爭 / 內耗', '内卷', '網路流行語', 'confirmed', 'involution'),
  ('擺爛 / 耍廢 / 與世無爭', '躺平', '網路流行語', 'confirmed', '『擺爛』為臺灣本土說法'),
  ('封鎖', '拉黑', '網路流行語', 'confirmed', 'block'),
  ('外送', '外卖', '網路流行語', 'confirmed', 'food delivery'),
  ('免運', '包邮', '網路流行語', 'confirmed', 'free shipping'),
  ('道地', '地道', '網路流行語', 'confirmed', '字序相反,authentic'),
  ('大概 / 我猜', '估计', '網路流行語', 'confirmed', '口語推測,如『我估計他不來』→『我猜他不來』'),
  ('推坑 / 燒到', '种草', '網路流行語', 'confirmed', '小紅書核心詞:被推薦而想買'),
  ('退坑 / 打消念頭', '拔草', '網路流行語', 'confirmed', '種草的反義'),
  ('出包 / 翻船 / 搞砸', '翻车', '網路流行語', 'confirmed', '搞砸、出糗'),
  ('破功 / 繃不住', '破防', '網路流行語', 'confirmed', '情緒被擊穿、忍不住'),
  ('最強 / 神作 / 封神', 'yyds（永远的神）', '網路流行語', 'confirmed', 'yyds=拼音縮寫'),
  ('太讚了 / 絕了', '绝绝子', '網路流行語', 'confirmed', '小紅書誇讚用語'),
  ('老兄 / 兄弟', '老铁', '網路流行語', 'confirmed', '直播稱呼,源自東北話'),
  ('各位 / 大家', '家人们', '網路流行語', 'confirmed', '直播帶貨稱呼:『家人们上链接』'),
  ('業配 / 導購', '带货', '網路流行語', 'confirmed', '直播帶貨=直播導購'),
  ('增加粉絲 / 掉粉', '涨粉 / 掉粉', '網路流行語', 'confirmed', NULL),
  ('推薦 / 推坑', '安利', '網路流行語', 'confirmed', '源自 Amway,意為大力推薦'),
  ('凹免費 / 免費拿', '白嫖', '網路流行語', 'confirmed', '只拿不付出'),
  ('糗到爆 / 丟臉丟到家', '社死（社会性死亡）', '網路流行語', 'confirmed', '極度尷尬'),
  ('變相炫耀 / 假謙虛炫富', '凡尔赛', '網路流行語', 'confirmed', '以抱怨包裝炫耀'),
  ('情緒低落 / 憂鬱', 'emo', '網路流行語', 'confirmed', '源自 emotional'),
  ('愛抬槓的人 / 唱反調', '杠精', '網路流行語', 'confirmed', '為反對而反對'),
  ('酸民 / 鍵盤戰士', '键盘侠', '網路流行語', 'confirmed', '『酸民』為臺灣本土說法'),
  ('帥哥 / 美女', '小哥哥 / 小姐姐', '網路流行語', 'confirmed', '電商/直播稱呼'),
  ('穩的 / 沒問題', '妥妥的', '網路流行語', 'confirmed', NULL),
  ('硬拚 / 卯起來', '死磕', '網路流行語', 'confirmed', NULL),
  ('時髦不時髦 / 潮不潮', 'city不city', '網路流行語', 'confirmed', '2024 中國十大流行語。美國博主『保保熊』來華旅遊常問『妹妹,city不city啊?』爆紅,意為時髦/洋氣/現代化與否'),
  ('上班的疲態 / 班相', '班味', '網路流行語', 'confirmed', '2024 十大流行語。指上班上到眼神疲憊、面容憔悴的樣子,源自網文『一旦上過班,你的氣質就會改變了』'),
  ('被牢牢吸住 / 挪不開眼', '硬控', '網路流行語', 'confirmed', '2024 十大流行語。原為遊戲『硬性控制』,轉為正面:『硬控我 X 秒』=某事物太吸引人、讓人短時間完全淪陷'),
  ('從容 / 淡定 / 不緊繃', '松弛感', '網路流行語', 'confirmed', '2024 十大流行語。面對壓力仍從容不焦慮的心理狀態或氛圍'),
  ('固定夥伴 / 咖', '搭子', '網路流行語', 'confirmed', '為特定目的結伴的淺社交關係,如『飯搭子』(一起吃飯)、『健身搭子』'),
  ('情緒支持 / 情緒滿足', '情绪价值', '網路流行語', 'confirmed', '能帶給人正向情緒的能力,如『情緒價值拉滿』'),
  ('荒謬 / 無厘頭 / 搞怪', '抽象', '網路流行語', 'confirmed', '網路義非本義,指荒誕搞笑、無厘頭的言行(『抽象文化』)'),
  ('真的假的', '尊嘟假嘟', '網路流行語', 'confirmed', '『真的假的』諧音賣萌梗,多配可愛貓狗照使用'),
  ('傻眼 / 無言(反諷式謝謝)', '栓Q', '網路流行語', 'confirmed', '英文 thank you 諧音(廣西陽朔大叔影片爆紅),實際多表無奈、吐槽而非道謝'),
  ('完蛋了 / 玩完了', '芭比Q了', '網路流行語', 'confirmed', 'barbecue(燒烤)諧音,意為『被烤了/完蛋了』'),
  ('偶像爆負面 / 人設崩壞', '塌房', '網路流行語', 'confirmed', '飯圈用語:偶像出現負面新聞或戀愛曝光,粉絲的『快樂老家』塌了'),
  ('頂級流量明星', '顶流', '網路流行語', 'confirmed', '飯圈用語:人氣最高的當紅偶像(顶级流量)'),
  ('嗑 CP / 支持配對', '磕CP', '網路流行語', 'confirmed', '飯圈用語:沉迷某對配對的互動,『kdl(磕到了)』『kswl(磕死我了)』'),
  ('頂尖 / 最高標準', '天花板', '網路流行語', 'confirmed', '某領域最強、無人能超越,如『顏值天花板』'),
  ('爆紅到圈外 / 廣為人知', '出圈', '網路流行語', 'confirmed', '從特定小圈子紅到大眾主流,相關詞『破圈』'),
  ('掌控 / 穩穩拿下', '拿捏', '網路流行語', 'confirmed', '『拿捏得死死的』=完全掌控、輕鬆搞定'),
  ('遙遙領先(多為反諷)', '遥遥领先', '網路流行語', 'confirmed', '源自華為發表會,網路多用於反諷式吹捧'),
  ('很入迷 / 上癮 / 衝動上腦', '上头', '網路流行語', 'confirmed', '讓人著迷欲罷不能;反義『下头』=掃興、倒胃口'),
  ('增能 / 加值 / 賦予能力', '赋能', '職場黑話', 'confirmed', '中國科技業黑話,經外商/新創外溢臺灣'),
  ('取得共識 / 同步', '对齐 / 拉齐', '職場黑話', 'confirmed', 'align'),
  ('檢討 / 回顧', '复盘', '職場黑話', 'confirmed', 'review/retrospective'),
  ('落實 / 實現', '落地', '職場黑話', 'confirmed', '『方案落地』=方案實行'),
  ('著力點 / 切入點', '抓手', '職場黑話', 'confirmed', NULL),
  ('完整循環 / 形成閉環', '闭环', '職場黑話', 'confirmed', 'closed loop'),
  ('細緻度 / 詳細程度', '颗粒度', '職場黑話', 'confirmed', 'granularity'),
  ('整合 / 打通', '拉通', '職場黑話', 'confirmed', NULL),
  ('領域 / 市場區塊', '赛道', '職場黑話', 'confirmed', '『這條賽道』=某產業或市場領域,如『押注 AI 賽道』'),
  ('對照 / 看齊 / 對比', '对标', '職場黑話', 'confirmed', 'benchmark;對標競品、對標一線大廠'),
  ('累積 / 積累 / 內化', '沉淀', '職場黑話', 'confirmed', '『經驗沉澱』『數據沉澱』=累積、萃取成資產'),
  ('根本原理 / 基本道理', '底层逻辑', '職場黑話', 'confirmed', 'underlying logic;事情運作的根本原理'),
  ('環節 / 流程串接', '链路', '職場黑話', 'confirmed', '『打通全鏈路』=串起整條流程/環節'),
  ('策略 / 做法 / 玩法', '打法', '職場黑話', 'confirmed', '『這套打法』=經營或執行策略'),
  ('生態系 / 生態圈', '生态', '職場黑話', 'confirmed', 'ecosystem;『做生態』=經營產品或夥伴生態系'),
  ('重複使用 / 沿用', '复用', '職場黑話', 'confirmed', 'reuse;『能力複用』=既有資源沿用到別處'),
  ('導流 / 帶客流', '引流', '職場黑話', 'confirmed', '把流量或客源導入某處'),
  ('轉換 / 轉換率', '转化', '職場黑話', 'confirmed', 'conversion;『提高轉化』=提高成交或註冊轉換率'),
  ('早安 / 早', '早上好', '問候', 'confirmed', '★臺灣習慣『早安』『早』,『早上好』為中國說法。同理晚安 vs 晚上好'),
  ('社區', '小区', '居住', 'confirmed', 'residential community'),
  ('屋主 / 住戶', '业主', '居住', 'confirmed', NULL),
  ('管委會 / 社區管理', '物业', '居住', 'confirmed', 'property management;臺灣『物業』少用'),
  ('建案', '楼盘', '居住', 'confirmed', 'housing development')
on conflict (tw, cn, category) do update set
  status = excluded.status,
  note   = excluded.note;
